### ISSUE TITLE
Support other element type than 8-bit integers

### ISSUE THREAD

**Issue by mmomtchev** [donmccurdy/ndarray-lanczos#98]
I would like to use it to resample DEM data which can be 16 bit integers or 32 bit floats but it is otherwise identical to image data.

**Comment by mmomtchev** [comment]
Alas, the method used (which includes bit shifting) is not extendable to floating point numbers

**Comment by donmccurdy** [comment]
Hi @mmomtchev! I think that'd be within scope for the project, and I'd be glad to review a PR if anyone would like to give it a try. It isn't something I'm planning to add to the library myself at this point, though.
